/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Casil;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.io.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author chris
 */
public class PokemonManagementGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(PokemonManagementGUI.class.getName());

    ArrayList<Pokemon> pokemonList = new ArrayList<>();
    final String FILE_NAME = "pokemon.dat";

    boolean isSaved = true; // track save status
    
    
    /**
     * Creates new form PokemonManagementGUI
     */
    public PokemonManagementGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ftid = new javax.swing.JTextField();
        ftname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ftlevel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ftweight = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ftability = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fttype = new javax.swing.JComboBox<>();
        btnadd = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnload = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 255, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("ID:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 40, -1));

        ftid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftidActionPerformed(evt);
            }
        });
        jPanel1.add(ftid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 160, -1));

        ftname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftnameActionPerformed(evt);
            }
        });
        jPanel1.add(ftname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 160, -1));

        jLabel2.setBackground(new java.awt.Color(0, 255, 153));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 50, -1));

        ftlevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftlevelActionPerformed(evt);
            }
        });
        jPanel1.add(ftlevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 160, -1));

        jLabel3.setBackground(new java.awt.Color(0, 255, 153));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Level:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 50, -1));

        jLabel4.setBackground(new java.awt.Color(0, 255, 153));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Type:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 50, -1));

        ftweight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftweightActionPerformed(evt);
            }
        });
        jPanel1.add(ftweight, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 160, -1));

        jLabel5.setBackground(new java.awt.Color(0, 255, 153));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Weight:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 50, -1));

        ftability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftabilityActionPerformed(evt);
            }
        });
        jPanel1.add(ftability, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 160, -1));

        jLabel6.setBackground(new java.awt.Color(0, 255, 153));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Ability:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 50, -1));

        fttype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fire", "Water", "Grass", "Lightning", "Wind", " " }));
        fttype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fttypeActionPerformed(evt);
            }
        });
        jPanel1.add(fttype, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 160, -1));

        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        jPanel1.add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Type", "Level", "Ability", "Weight"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, 180));

        btnload.setText("Load");
        btnload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloadActionPerformed(evt);
            }
        });
        jPanel1.add(btnload, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("ADD POKEMON");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        delete.setText("delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ftidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftidActionPerformed

    private void ftnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftnameActionPerformed

    private void ftlevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftlevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftlevelActionPerformed

    private void ftweightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftweightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftweightActionPerformed

    private void ftabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftabilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftabilityActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
    if (ftid.getText().isEmpty() || ftname.getText().isEmpty()
            || ftlevel.getText().isEmpty() || ftability.getText().isEmpty()
            || ftweight.getText().isEmpty()) {

        JOptionPane.showMessageDialog(this, "All fields must be filled!");
        return;
    }

    int id, level;
    double weight;

    try {
        id = Integer.parseInt(ftid.getText());
        level = Integer.parseInt(ftlevel.getText());
        weight = Double.parseDouble(ftweight.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
                "ID & Level must be integers\nWeight must be decimal");
        return;
    }


    loadFromFile();

    for (Pokemon p : pokemonList) {
        if (p.getId() == id) {
            JOptionPane.showMessageDialog(this,
                    "Duplicate Pokémon ID not allowed!");
            return;
        }
    }


    pokemonList.add(new Pokemon(
            id,
            ftname.getText(),
            fttype.getSelectedItem().toString(),
            level,
            ftability.getText(),
            weight
    ));

    isSaved = false;

    clearFields();

    JOptionPane.showMessageDialog(this,
            "Pokemon added!\nClick SAVE then LOAD to display.");

    }//GEN-LAST:event_btnaddActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
           if (pokemonList.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Table is empty, can't save!");
            return;
        }

        if (isSaved) {
            JOptionPane.showMessageDialog(this,
                    "Already saved to pokemon.dat!");
            return;
        }

        saveToFile();
        isSaved = true;

        JOptionPane.showMessageDialog(this,
                "Pokemon list saved successfully!");
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloadActionPerformed
        // TODO add your handling code here:
     loadFromFile();
     refreshTable();

    }//GEN-LAST:event_btnloadActionPerformed

    private void fttypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fttypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fttypeActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here
                if (pokemonList.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Can't delete because table is empty!");
            return;
        }

        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this,
                    "Select a row to delete!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Delete selected Pokémon?",
                "Confirm", JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) return;

        pokemonList.remove(row);
        saveToFile();
        isSaved = true;

        refreshTable();
        JOptionPane.showMessageDialog(this, "Pokemon deleted!");
    }//GEN-LAST:event_deleteActionPerformed
    
    // SAVE TO FILE 
private void saveToFile() {
        try (ObjectOutputStream oos =
                     new ObjectOutputStream(new FileOutputStream(FILE_NAME))) {
            oos.writeObject(pokemonList);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving file!");
        }
}

    private void loadFromFile() {
        File file = new File(FILE_NAME);
        if (!file.exists()) {
            pokemonList = new ArrayList<>();
            return;
        }
        try (ObjectInputStream ois =
                     new ObjectInputStream(new FileInputStream(FILE_NAME))) {
            pokemonList = (ArrayList<Pokemon>) ois.readObject();
        } catch (Exception e) {
            pokemonList = new ArrayList<>();
        }
    }

        //UTILITIES
    private void refreshTable() {
        DefaultTableModel model =
                (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for (Pokemon p : pokemonList) {
            model.addRow(new Object[]{
                    p.getId(), p.getName(), p.getType(),
                    p.getLevel(), p.getAbility(), p.getWeight()
            });
        }
    }
// CLEAR INPUT FIELDS
private void clearFields() {
    ftid.setText("");
    ftname.setText("");
    ftlevel.setText("");
    ftweight.setText("");
    ftability.setText("");
    fttype.setSelectedIndex(0);
}

 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PokemonManagementGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnload;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton delete;
    private javax.swing.JTextField ftability;
    private javax.swing.JTextField ftid;
    private javax.swing.JTextField ftlevel;
    private javax.swing.JTextField ftname;
    private javax.swing.JComboBox<String> fttype;
    private javax.swing.JTextField ftweight;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
